# Generated by Django 4.1.4 on 2022-12-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=96)),
                ('image_url', models.URLField()),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
    ]
